learning_log/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls'))
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #  homepage
    path('', views.index, name='index'),
    # topics page
    path('topics/', views.topics, name='topics'),
    # page for one topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # new topic starter page
    path('new_topic/', views.new_topic, name='new_topic'),
    # new entry page
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    # entries editing page
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""URLs for users paths"""

from django.urls import path, include
from . import views


app_name = 'users'
urlpatterns = [
    # URL for authorization by default
    path('', include('django.contrib.auth.urls')),
    # registration page
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f'{self.text[:50]}...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


def index(request):
    """learning_logs homepage"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    # shows list of topics
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    # shows the only topic and all theirs posts
    topic = get_object_or_404(id=topic_id)
    # if user own for this topic
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Defines new topic"""
    if request.method != 'POST':
        # creates new form, if post is empty
        form = TopicForm()
    else:
        # creates form if form POST
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # show empty of invalid form
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Adds a new entry for topic"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        #  creates new form, if post is empty
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit current entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner !=request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    # registration new user
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        # working with filled form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # login and redirecting to homepage
            login(request, new_user)
            return redirect('learning_logs:index')

    # show empty or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,
            shrink-to-fit=no">
        <title>Learning Lol</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}

    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                Learning Lols
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <h3>Edit entry:</h3>
{% endblock page_header %}

{% block content %}
<form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Learning lols!</h1>

        <p class="lead">This one is for those who are crazy!</p>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
       role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <h3>New entry:</h3>
{% endblock page_header %}

{% block content %}
<form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% load bootstrap4%}

{% block page_header %}
    <h3>Add a new topic:</h3>
{% endblock page_header %}

{% block content %}
<form method="post" action="{% url 'learning_logs:new_topic' %}"  class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
{% for entry in entries %}
    <div class="card mb-3">
        <h4 class="card-header">
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
            </small>
        </h4>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div>
{% empty %}
    <li>There are no entry for this topic yet!</li>
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1>Topic</h1>
{% endblock page_header%}

{% block content %}

  <p>Topics</p>
  <ul>
      {% for topic in topics %}
      <li><h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3></li>
      {% empty %}
      <li><h3>No topics have been added yet.</h3>></li>
      {% endfor %}
  </ul>

<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}